title: Meteor Community
subtitle: Meteor Community Packages
description: Community site for Meteor Community Packages
versions:
  - '1'
versioned-netlify-redirects:
  netlify_site_id: meteor-community
sidebar_categories:
  null:
    - index
    - news
  Projects:
    - projects/index
    - projects/newsletter
    - projects/slack
    - projects/meetups
    - projects/impact
    - projects/packosphere
    - projects/testing
  Packages:
    - packages/index
    - packages/collection2
    - packages/roles
    - packages/autoform
    - packages/collection-hooks
    - packages/method-hooks
    - packages/picker
    - packages/publish-composite
    - packages/fast-render
    - packages/inject-data
    - packages/stylus
    - packages/stratosphere
    - packages/link-accounts
    - packages/api-untethered
    - packages/check-npm-version
    - packages/push
    - packages/partitioner
    - packages/minifiers-autoprefix
    - packages/meteor-packages
    - packages/meteor-scss
    - packages/postcss
    - packages/desktop
    - packages/timesync
    - packages/react-router-ssr
    - packages/elastic-apm
    - packages/user-status
github_repo: Meteor-Community-Packages/website

url: http://meteorjs.community/
root: /

source_dir: community
content_root: community

highlight:
  enable: false

language:
  - en
  - ko-KR
  - ja-JP
  - cs-CZ
  - de-DE

i18n_dir: :lang

logo:
  title:
  subtitle: Community

external_link:
  enable: true
  field: site
  exclude: []

theme: 'meteor'
default_layout: page

deploy:
  type: git
  repo: https://github.com/Meteor-Community-Packages/website
  branch: master
