github_repo: Meteor-Community-Packages/website
description: Community site for Meteor Community Packages
author: null
language:
  - en
  - ko-KR
  - ja-JP
  - cs-CZ
  - de-DE
timezone: null
apis:
  gtm: GTM-MBQ369M
  marketo: 627-RVJ-941
  segment: zQx6cQifkTU79E3L0XAnmrOXP2A5bC6r
  docsearch:
    apiKey: 85d8a989beb6790642e6edd6ea380788
    indexName: meteor
content_root: community
css_bundle: meteor
nav_class: dark
favicon: images/favicon-meteor.png
logo:
  nav_mobile: images/meteor-cloud.png
  url: ''
  title: null
  subtitle: Community
nav_links:
  Meteor Cloud:
    url: https://www.meteor.com/cloud
    partial: illustration-guide
    target: _new
    active: false
  Tutorials:
    url: https://www.meteor.com/developers/tutorials
    partial: illustration-guide
    target: _new
    active: false
  Guide:
    url: https://guide.meteor.com
    partial: illustration-compass
    active: false
  API Docs:
    url: https://docs.meteor.com
    partial: illustration-logs
    active: false
  Forums:
    url: https://forums.meteor.com/
    partial: illustration-support
    target: _new
    active: false
social_links:
  github: https://github.com/meteor
  twitter: '@meteorjs'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: community
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: page
titlecase: false
external_link:
  enable: true
  field: site
  exclude: []
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
theme: meteor
marked:
  breaks: false
highlight:
  enable: false
prism_plus:
  enable: true
  mode: preprocess
  default_preset:
    lineno: true
deploy:
  type: git
  repo: https://github.com/Meteor-Community-Packages/website
  branch: master
browsersync:
  ghostMode: false
title: Meteor Community
subtitle: Meteor Community Packages
versions:
  - '1'
versioned-netlify-redirects:
  netlify_site_id: meteor-community
sidebar_categories:
  'null':
    - index
    - news
  Projects:
    - projects/index
    - projects/newsletter
    - projects/slack
    - projects/meetups
    - projects/packosphere
    - projects/testing
    - projects/impact
  Packages:
    - packages/api-untethered
    - packages/autoform
    - packages/check-npm-version
    - packages/collection-hooks
    - packages/collection2
    - packages/desktop
    - packages/elastic-apm
    - packages/fast-render
    - packages/index
    - packages/inject-data
    - packages/link-accounts
    - packages/meteor-packages
    - packages/meteor-scss
    - packages/method-hooks
    - packages/minifiers-autoprefix
    - packages/partitioner
    - packages/picker
    - packages/postcss
    - packages/publish-composite
    - packages/push
    - packages/react-router-ssr
    - packages/roles
    - packages/stratosphere
    - packages/stylus
    - packages/tabular
    - packages/timesync
    - packages/user-status
url: http://meteorjs.community/
